project:
  type: website

website:
  site-url: "https://epiverse-trace.github.io/etstats"
  title: "Epiverse-TRACE statistics"
  navbar:
    left:
      - index.qmd
      - github-statistics.qmd
      - citations.qmd
      - text: "Reports"
        menu:
          - text: "Wellcome Phase 1"
            href: contributions_dashboard.qmd
  google-analytics: "G-XZ471458FQ"

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
