---
title: "CRAN statistics"
date: "`r Sys.Date()`"
aliases:
  - articles/cran-statistics.html
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r}
et_cran_pkgs <- "https://epiverse-trace.r-universe.dev/api/packages/" |>
  jsonlite::fromJSON() |>
  dplyr::filter(
    `_registered`,
    `_cranurl`
    ) |>
  dplyr::pull(Package) |>
  sort()
```

We currently have `r length(et_cran_pkgs)` Epiverse-TRACE packages on CRAN:

```{r, results='asis'}
cat(paste0("- [", et_cran_pkgs, "](https://cran.r-project.org/package=", et_cran_pkgs, ")"), sep = "\n")
```

```{r}
et_cran_pkgs_string <- glue::glue_collapse(et_cran_pkgs, sep = ",")
yesterday <- Sys.Date() - 1
```

```{r}
et_cran_stats <- "https://cranlogs.r-pkg.org/downloads/daily/2022-05-13:{yesterday}/{et_cran_pkgs_string}" |>
  glue::glue() |>
  jsonlite::fromJSON() |>
  dplyr::select(-start, -end) |>
  tidyr::unnest(downloads) |>
  dplyr::mutate(day = as.Date(day))
```

```{r}
et_cran_versions <- et_cran_pkgs |>
  purrr::map(pkgsearch::cran_package_history) |>
  purrr::list_rbind() |>
  dplyr::transmute(
    package = Package,
    version = Version,
    day = as.Date(date)
  )
```

In total, Epiverse-TRACE packages on CRAN have been downloaded `r sum(et_cran_stats$downloads)` times.

Below is a visualization of the breakdown of this grand total over time.

```{r aggregated-downloads-plot, fig.alt="Summed cumulative downloads of Epiverse-TRACE on CRAN"}
library(ggplot2)
theme_set(theme_minimal())

et_cran_stats |>
  dplyr::summarise(downloads = sum(downloads), .by = day) |>
  dplyr::arrange(day) |>
  dplyr::mutate(`Cumulative downloads` = cumsum(downloads)) |>
  ggplot(aes(x = day, y = `Cumulative downloads`)) +
    geom_line() +
    labs(
      title = "Cumulative downloads of Epiverse-TRACE suite on CRAN",
      caption = "Data from RStudio CRAN mirror, via cranlogs.r-pkg.org"
    )
```

And the same breakdown by package:

```{r package-downloads-plot, fig.alt=glue::glue("Cumulative downloads of Epiverse-TRACE on CRAN ({toString(et_cran_pkgs)})")}
et_cran_stats |>
  dplyr::full_join(et_cran_versions, by = c("package", "day")) |>
  dplyr::mutate(`Cumulative downloads` = cumsum(downloads), .by = package) |>
  ggplot(aes(x = day, y = `Cumulative downloads`, color = package)) +
    geom_line() +
    geom_point(data = ~ dplyr::filter(., !is.na(version))) +
    labs(
      title = "Cumulative downloads of Epiverse-TRACE packages on CRAN",
      subtitle = "Points indicate new CRAN releases",
      caption = "Data from RStudio CRAN mirror, via cranlogs.r-pkg.org"
    ) +
    scale_colour_viridis_d(option = "turbo")
```

```{r}
# Break down by year in a table
et_cran_stats |>
  dplyr::mutate(year = lubridate::year(day)) |>
  dplyr::group_by(year, package) |>
  dplyr::summarize(downloads = sum(downloads)) |>
  tidyr::pivot_wider(names_from = year, values_from = downloads) |>
  janitor::adorn_totals("row") |>
  dplyr::mutate(dplyr::across(dplyr::everything(), ~ ifelse(is.na(.), "", .))) |>
  knitr::kable()
```

