```{r get-latest-{{ visit }}}
latest_{{ visit }} <- repos |> 
  purrr::map(function(repo) {
    c(
      package = basename(repo),
      gh::gh("/repos/{repo}/traffic/{{ visit }}", repo = repo)[c("count", "uniques")]
    )
  })
```

```{r load-history-{{ visit }}}
if (file.exists(here::here("inst", "extdata", "traffic", "{{ visit }}.json"))) {
  history_{{ visit }} <- jsonlite::read_json(
    here::here("inst", "extdata", "traffic", "{{ visit }}.json")
  )
} else {
  history_{{ visit }} <- NULL
}
```

```{r merge-latest-history-{{ visit }}}
all_{{ visit }} <- c(
  setNames(list(latest_{{ visit }}), format(Sys.Date()+1)), 
  history_{{ visit }}
)
```

```{r save-date-{{ visit }}}
jsonlite::write_json(
  all_{{ visit }},
  here::here("inst", "extdata", "traffic", "{{ visit }}.json"),
  pretty = TRUE,
  auto_unbox = TRUE
)
```

```{r plot-{{ visit }}, eval = FALSE}
all_{{ visit }} |> 
  purrr::imap(\(x, idx) purrr::modify(x, function(y) { y$date = idx; return(y) })) |> 
  dplyr::bind_rows() |> 
  dplyr::group_by(package) |> 
  ggplot(aes(x = date, y = count, color = package)) +
    geom_point()
```
