---
title: "Visits and downloads of GitHub repositories"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visits and downloads of GitHub repositories}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>"
)
```

```{r setup}
library(gh)
library(ggplot2)
```

```{r}
org <- "epiverse-trace"
```

```{r}
repos <- gh::gh(
  "/orgs/{org}/repos",
  org = org,
  per_page = 100
) |> 
  purrr::discard(\(x) x$private) |>
  purrr::map_chr("full_name")
```

## Clones

```{r, results='asis'}
knitr::knit_expand(
  "_visit_stats.Rmd",
  visit = "clones"
) |> 
  knitr::knit(text = _, quiet = TRUE) |> 
  cat()
```

## Views

```{r, results='asis'}
knitr::knit_expand(
  "_visit_stats.Rmd",
  visit = "views"
) |> 
  knitr::knit(text = _, quiet = TRUE) |> 
  cat()
```

## Referrals

```{r}
latest_referrals <- repos |> 
  purrr::map(function(repo) {
    c(
      package = basename(repo),
      gh::gh("/repos/{repo}/traffic/popular/referrers", repo = repo)
    )
  })
```

```{r load-history-referrals}
if (file.exists(here::here("inst", "extdata", "traffic", "referrals.json"))) {
  history_referrals <- jsonlite::read_json(
    here::here("inst", "extdata", "traffic", "referrals.json")
  )
} else {
  history_referrals <- NULL
}
```

```{r merge-latest-history-{{ visit }}}
all_referrals <- c(
  setNames(list(latest_referrals), format(Sys.Date()+1)), 
  history_referrals
)
```

```{r save-date-{{ visit }}}
jsonlite::write_json(
  all_referrals,
  here::here("inst", "extdata", "traffic", "referrals.json"),
  pretty = TRUE,
  auto_unbox = TRUE
)
```
